# Generated by Django 4.1.3 on 2022-11-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
